######################################################################
# Automatically generated by qmake (2.01a) jeu. févr. 10 18:29:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mygraphicsview.h
SOURCES += main.cpp mainwindow.cpp mygraphicsview.cpp
