#ifndef _BABAR_PARAM_TALKS_H
#define _BABAR_PARAM_TALKS_H

#define TALKS_BACKGROUND_SIZE_H 160
#define TALKS_BACKGROUND_OFFSET_W 5
#define TALKS_BACKGROUND_OFFSET_H 5
#define TALKS_BACKGROUND_R 0
#define TALKS_BACKGROUND_G 0
#define TALKS_BACKGROUND_B 0
#define TALKS_TEXTSPECIAL_R 255
#define TALKS_TEXTSPECIAL_G 0
#define TALKS_TEXTSPECIAL_B 0
#define TALKS_FRAME_R 0
#define TALKS_FRAME_G 0
#define TALKS_FRAME_B 0
#define TALKS_TEXT_SIZE 20
#define TALKS_TEXT_R 255
#define TALKS_TEXT_G 200
#define TALKS_TEXT_B 0
#define ALPHA_TALKS_BACKGROUND 200




#endif
